name: airflowTests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: airflow tests
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.12"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip &&
          pip install \
            -r requirements_test.txt \
            -r requirements_local.txt \
            -r requirements_airflow.txt
      - name: Run pytest on airflow/tests
        run: pytest -v tests/test_airflow_imports.py
